#!/bin/bash
# ═══════════════════════════════════════════════════════════
# ModESP Cloud — Deploy Phase 4: Dynamic MQTT Auth
# Run on VPS as root (or with sudo)
# ═══════════════════════════════════════════════════════════
set -euo pipefail

MODESP_DIR="/opt/modesp-cloud"
BACKEND_DIR="$MODESP_DIR/backend"
WEBUI_DIR="$MODESP_DIR/webui"
MOSQUITTO_CONF="/etc/mosquitto/conf.d/modesp.conf"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# ── Pre-checks ────────────────────────────────────────────
info "=== Phase 4: Dynamic MQTT Auth Deployment ==="

[ -d "$MODESP_DIR" ] || error "ModESP Cloud not found at $MODESP_DIR"

# Check required env vars
if [ -z "${MQTT_BOOTSTRAP_PASSWORD:-}" ]; then
    echo ""
    warn "MQTT_BOOTSTRAP_PASSWORD not set."
    echo "  This is the shared password all ESP32 devices use for initial connection."
    echo "  Generate one: openssl rand -base64 16"
    echo "  Then set in $BACKEND_DIR/.env:"
    echo "    MQTT_BOOTSTRAP_PASSWORD=<your_password>"
    echo ""
    read -p "Enter MQTT_BOOTSTRAP_PASSWORD now (or Ctrl+C to abort): " MQTT_BOOTSTRAP_PASSWORD
    echo "MQTT_BOOTSTRAP_PASSWORD=$MQTT_BOOTSTRAP_PASSWORD" >> "$BACKEND_DIR/.env"
    info "Added to .env"
fi

# ── Step 1: Git pull ──────────────────────────────────────
info "Step 1: Pulling latest code..."
cd "$MODESP_DIR"
git pull origin main
info "Code updated."

# ── Step 2: Install backend dependencies ──────────────────
info "Step 2: Installing backend dependencies..."
cd "$BACKEND_DIR"
npm install --production
info "Dependencies installed."

# ── Step 3: Run migration 008 ────────────────────────────
info "Step 3: Running migration 008_mqtt_auth.sql..."
sudo -u postgres psql -d modesp_cloud -f "$BACKEND_DIR/src/db/migrations/008_mqtt_auth.sql"
info "Migration 008 applied."

# ── Step 4: Build mosquitto-go-auth (if not built) ───────
if [ ! -f /usr/lib/mosquitto/go-auth.so ]; then
    info "Step 4: Building mosquitto-go-auth plugin..."
    apt install -y golang-go libmosquitto-dev pkg-config git

    TMPDIR=$(mktemp -d)
    cd "$TMPDIR"
    git clone --depth 1 https://github.com/iegomez/mosquitto-go-auth.git
    cd mosquitto-go-auth
    make
    cp go-auth.so /usr/lib/mosquitto/go-auth.so
    cd /
    rm -rf "$TMPDIR"
    info "mosquitto-go-auth built and installed."
else
    info "Step 4: mosquitto-go-auth already installed, skipping."
fi

# ── Step 5: Create PostgreSQL read-only user ──────────────
info "Step 5: Creating PostgreSQL read-only user for Mosquitto..."
read -sp "Enter password for modesp_mqtt_ro PostgreSQL user: " PG_RO_PASS
echo ""

sudo -u postgres psql -d modesp_cloud <<EOF
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'modesp_mqtt_ro') THEN
        CREATE USER modesp_mqtt_ro WITH PASSWORD '$PG_RO_PASS';
    ELSE
        ALTER USER modesp_mqtt_ro WITH PASSWORD '$PG_RO_PASS';
    END IF;
END
\$\$;
GRANT CONNECT ON DATABASE modesp_cloud TO modesp_mqtt_ro;
GRANT USAGE ON SCHEMA public TO modesp_mqtt_ro;
GRANT SELECT ON devices, tenants TO modesp_mqtt_ro;
EOF
info "PostgreSQL user modesp_mqtt_ro ready."

# ── Step 6: Update Mosquitto config ──────────────────────
info "Step 6: Updating Mosquitto configuration..."

# Backup current config
if [ -f "$MOSQUITTO_CONF" ]; then
    cp "$MOSQUITTO_CONF" "${MOSQUITTO_CONF}.bak.$(date +%Y%m%d_%H%M%S)"
    info "Backed up current config."
fi

# Write new config with actual password
cat > "$MOSQUITTO_CONF" <<MQTTEOF
# ═══════════════════════════════════════════════════════════
# ModESP Cloud — Mosquitto з mosquitto-go-auth
# Generated by deploy-mqtt-auth.sh on $(date -Iseconds)
# ═══════════════════════════════════════════════════════════

per_listener_settings true

# ── Listener 1: Backend (localhost, без auth) ─────────────
listener 1883 127.0.0.1
allow_anonymous true

# ── Listener 2: ESP32 devices (TLS + plugin auth) ────────
listener 8883 0.0.0.0
allow_anonymous false

# TLS
cafile /etc/mosquitto/certs/ca.crt
certfile /etc/mosquitto/certs/server.crt
keyfile /etc/mosquitto/certs/server.key
tls_version tlsv1.2

# Auth plugin
auth_plugin /usr/lib/mosquitto/go-auth.so
auth_opt_backends postgres
auth_opt_hasher bcrypt
auth_opt_hasher_cost 12

# Cache
auth_opt_cache true
auth_opt_cache_type go-cache
auth_opt_auth_cache_seconds 300
auth_opt_acl_cache_seconds 60
auth_opt_auth_jitter_seconds 10
auth_opt_acl_jitter_seconds 5

# PostgreSQL
auth_opt_pg_host localhost
auth_opt_pg_port 5432
auth_opt_pg_dbname modesp_cloud
auth_opt_pg_user modesp_mqtt_ro
auth_opt_pg_password $PG_RO_PASS
auth_opt_pg_sslmode disable
auth_opt_pg_connect_tries 5

# ── SQL Queries ───────────────────────────────────────────

# User: bcrypt hash by mqtt_username
auth_opt_pg_userquery SELECT mqtt_password_hash FROM devices WHERE mqtt_username = \$1 AND status != 'disabled' AND mqtt_password_hash IS NOT NULL LIMIT 1

# Superuser: nobody (backend on localhost bypasses plugin)
auth_opt_pg_superquery SELECT 0 FROM devices WHERE 1 = 0

# ACL: devices can publish state/status/heartbeat, subscribe to cmd
auth_opt_pg_aclquery SELECT topic FROM ( SELECT CASE WHEN d.status = 'pending' THEN 'modesp/v1/pending/' || d.mqtt_device_id WHEN d.status = 'active' THEN 'modesp/v1/' || t.slug || '/' || d.mqtt_device_id END AS prefix FROM devices d LEFT JOIN tenants t ON t.id = d.tenant_id WHERE d.mqtt_username = \$1 AND d.status IN ('pending', 'active') ) sub CROSS JOIN ( SELECT '/state/+' AS suffix, 2 AS rw UNION ALL SELECT '/status', 2 UNION ALL SELECT '/heartbeat', 2 UNION ALL SELECT '/cmd/+', 1 ) acl WHERE acl.rw = \$2 AND sub.prefix IS NOT NULL

# ── Persistence + Logging ─────────────────────────────────
persistence true
persistence_location /var/lib/mosquitto/
max_connections 500
message_size_limit 1024
log_dest syslog
log_type error
log_type warning
connection_messages true
MQTTEOF

info "Mosquitto config updated."

# ── Step 7: Provision existing devices ────────────────────
info "Step 7: Provisioning MQTT credentials for existing devices..."
cd "$BACKEND_DIR"
echo ""
echo "  Dry run first (no changes):"
node scripts/provision-mqtt-creds.js
echo ""
read -p "Apply? (yes/no): " APPLY
if [ "$APPLY" = "yes" ]; then
    node scripts/provision-mqtt-creds.js --apply
    info "Credentials provisioned."
else
    warn "Skipped. Run manually later: node scripts/provision-mqtt-creds.js --apply"
fi

# ── Step 8: Build WebUI ──────────────────────────────────
info "Step 8: Building WebUI..."
cd "$WEBUI_DIR"
npm install
npm run build
info "WebUI built."

# ── Step 9: Restart services ─────────────────────────────
info "Step 9: Restarting services..."
systemctl restart mosquitto
sleep 2
systemctl restart modesp-backend
info "Services restarted."

# ── Step 10: Verify ──────────────────────────────────────
info "Step 10: Verification..."
echo ""

# Check Mosquitto
if systemctl is-active --quiet mosquitto; then
    echo -e "  Mosquitto: ${GREEN}running${NC}"
else
    echo -e "  Mosquitto: ${RED}FAILED${NC}"
    journalctl -u mosquitto -n 10 --no-pager
fi

# Check backend
sleep 3
if curl -sf http://localhost:3000/api/health > /dev/null 2>&1; then
    echo -e "  Backend:   ${GREEN}healthy${NC}"
else
    echo -e "  Backend:   ${RED}FAILED${NC}"
    journalctl -u modesp-backend -n 10 --no-pager
fi

# Test MQTT auth (localhost should still work)
if mosquitto_pub -h localhost -p 1883 -t "test/deploy" -m "ok" 2>/dev/null; then
    echo -e "  MQTT (localhost): ${GREEN}OK${NC}"
else
    echo -e "  MQTT (localhost): ${RED}FAILED${NC}"
fi

echo ""
info "=== Deployment complete ==="
echo ""
echo "Next steps:"
echo "  1. For existing ESP32 devices: enter new MQTT credentials"
echo "     via local WebUI (one-time, until firmware supports _set_mqtt_creds)"
echo "  2. Flash updated firmware (with _set_mqtt_creds handler) to devices"
echo "  3. New devices will auto-provision on assign (zero-touch)"
echo ""
echo "Rollback:"
echo "  cp ${MOSQUITTO_CONF}.bak.* $MOSQUITTO_CONF"
echo "  systemctl restart mosquitto"
echo ""
