'use strict';

/**
 * Invoice PDF (plan epic 2.2). One A4 page per invoice: seller requisites
 * (billing_settings), buyer (snapshot taken at issue time), period, the
 * lines — for a partner one line per client organisation — the total and the
 * payment purpose the customer copies into the bank transfer. Localised
 * uk / en / pl / de like the HACCP report; the language is the payer
 * organisation's (tenant_settings.locale).
 */

const pdfmake   = require('pdfmake/build/pdfmake');
const vfs_fonts = require('pdfmake/build/vfs_fonts');
const { pickLocale, INTL_TAG } = require('../lib/locale');

pdfmake.addVirtualFileSystem(vfs_fonts);

// scripts/check-locales.js fails CI when one language lacks a key.
const STRINGS = {
  uk: {
    title:        'Рахунок-фактура',
    number:       'Номер',
    issued:       'Дата',
    due:          'Оплатити до',
    period:       'Період',
    seller:       'Постачальник',
    buyer:        'Платник',
    tax_id:       'ЄДРПОУ / ІПН',
    iban:         'IBAN',
    bank:         'Банк',
    address:      'Адреса',
    email:        'E-mail',
    col_n:        '№',
    col_desc:     'Найменування',
    col_qty:      'К-сть',
    col_unit:     'Ціна',
    col_amount:   'Сума',
    total:        'Разом до сплати',
    purpose:      'Призначення платежу',
    purpose_text: (n) => `Оплата за рахунком ${n}, послуги моніторингу ModESP Cloud`,
    kind_base:        (plan) => `Абонплата за планом «${plan}»`,
    kind_controllers: (org) => `Моніторинг контролерів — ${org}`,
    kind_sites:       (org) => `Об'єкти (точки) — ${org}`,
    unit_month:   'міс.',
    unit_pcs:     'шт.',
    status_paid:  'ОПЛАЧЕНО',
    status_void:  'АНУЛЬОВАНО',
    footer:       'Сформовано ModESP Cloud',
    page:         'Стор.',
    of:           'з',
  },
  en: {
    title:        'Invoice',
    number:       'Number',
    issued:       'Date',
    due:          'Due by',
    period:       'Period',
    seller:       'Supplier',
    buyer:        'Payer',
    tax_id:       'Tax ID',
    iban:         'IBAN',
    bank:         'Bank',
    address:      'Address',
    email:        'E-mail',
    col_n:        '#',
    col_desc:     'Description',
    col_qty:      'Qty',
    col_unit:     'Unit price',
    col_amount:   'Amount',
    total:        'Total due',
    purpose:      'Payment reference',
    purpose_text: (n) => `Payment of invoice ${n}, ModESP Cloud monitoring services`,
    kind_base:        (plan) => `Subscription fee, plan “${plan}”`,
    kind_controllers: (org) => `Controller monitoring — ${org}`,
    kind_sites:       (org) => `Sites — ${org}`,
    unit_month:   'mo.',
    unit_pcs:     'pcs',
    status_paid:  'PAID',
    status_void:  'VOID',
    footer:       'Generated by ModESP Cloud',
    page:         'Page',
    of:           'of',
  },
  pl: {
    title:        'Faktura',
    number:       'Numer',
    issued:       'Data',
    due:          'Termin płatności',
    period:       'Okres',
    seller:       'Sprzedawca',
    buyer:        'Płatnik',
    tax_id:       'NIP',
    iban:         'IBAN',
    bank:         'Bank',
    address:      'Adres',
    email:        'E-mail',
    col_n:        'Lp.',
    col_desc:     'Nazwa',
    col_qty:      'Ilość',
    col_unit:     'Cena',
    col_amount:   'Kwota',
    total:        'Razem do zapłaty',
    purpose:      'Tytuł przelewu',
    purpose_text: (n) => `Zapłata za fakturę ${n}, usługi monitoringu ModESP Cloud`,
    kind_base:        (plan) => `Abonament, plan „${plan}”`,
    kind_controllers: (org) => `Monitoring sterowników — ${org}`,
    kind_sites:       (org) => `Obiekty — ${org}`,
    unit_month:   'mies.',
    unit_pcs:     'szt.',
    status_paid:  'ZAPŁACONO',
    status_void:  'ANULOWANO',
    footer:       'Wygenerowano przez ModESP Cloud',
    page:         'Str.',
    of:           'z',
  },
  de: {
    title:        'Rechnung',
    number:       'Nummer',
    issued:       'Datum',
    due:          'Fällig am',
    period:       'Zeitraum',
    seller:       'Lieferant',
    buyer:        'Zahler',
    tax_id:       'Steuernummer',
    iban:         'IBAN',
    bank:         'Bank',
    address:      'Adresse',
    email:        'E-Mail',
    col_n:        'Nr.',
    col_desc:     'Bezeichnung',
    col_qty:      'Menge',
    col_unit:     'Einzelpreis',
    col_amount:   'Betrag',
    total:        'Gesamtbetrag',
    purpose:      'Verwendungszweck',
    purpose_text: (n) => `Zahlung der Rechnung ${n}, ModESP Cloud Überwachungsdienste`,
    kind_base:        (plan) => `Grundgebühr, Tarif „${plan}“`,
    kind_controllers: (org) => `Reglerüberwachung — ${org}`,
    kind_sites:       (org) => `Standorte — ${org}`,
    unit_month:   'Mon.',
    unit_pcs:     'Stk.',
    status_paid:  'BEZAHLT',
    status_void:  'STORNIERT',
    footer:       'Erstellt von ModESP Cloud',
    page:         'Seite',
    of:           'von',
  },
};

function strings(lang) { return STRINGS[pickLocale(lang)]; }

/** "1 250,00 ₴" / "UAH 1,250.00" in the locale's own conventions. */
function formatMoney(value, currency = 'UAH', lang = 'uk') {
  const n = Number(value) || 0;
  try {
    return new Intl.NumberFormat(INTL_TAG[pickLocale(lang)], { style: 'currency', currency, minimumFractionDigits: 2 }).format(n);
  } catch {
    return `${n.toFixed(2)} ${currency}`;
  }
}

function formatDate(value, lang = 'uk') {
  if (!value) return '—';
  try {
    return new Date(value).toLocaleDateString(INTL_TAG[pickLocale(lang)], { day: '2-digit', month: '2-digit', year: 'numeric', timeZone: 'UTC' });
  } catch {
    return String(value).slice(0, 10);
  }
}

/** Human description of one invoice line, in the invoice language. */
function lineDescription(line, S) {
  const org = line.tenant_name || '';
  switch (line.kind) {
    case 'base':        return S.kind_base(line.plan_name || line.plan || '');
    case 'controllers': return S.kind_controllers(org);
    case 'sites':       return S.kind_sites(org);
    default:            return line.description || line.kind || '';
  }
}

/** A labelled block; a row without a label (the name) prints bold on its own. */
function block(title, rows) {
  const body = rows.filter(r => r && r[1]).map(([k, v]) => (k
    ? { text: [{ text: `${k}: `, color: '#666666' }, String(v)], margin: [0, 1, 0, 1] }
    : { text: String(v), bold: true, margin: [0, 1, 0, 2] }));
  const head = title ? [{ text: title, bold: true, fontSize: 10, margin: [0, 0, 0, 4] }] : [];
  return { stack: [...head, ...body], width: '*' };
}

/**
 * @param {object} p
 * @param {object} p.invoice   invoice row (number, period_start, period_end, issued_at, due_at, lines, amount, currency, status, buyer)
 * @param {object} p.seller    billing_settings row
 * @param {string} p.lang
 */
function buildDocument({ invoice, seller = {}, lang }) {
  const S = strings(lang);
  const currency = invoice.currency || 'UAH';
  const lines = Array.isArray(invoice.lines) ? invoice.lines : [];
  const buyer = invoice.buyer || {};
  const number = invoice.number;

  const tableBody = [
    [S.col_n, S.col_desc, { text: S.col_qty, alignment: 'right' }, { text: S.col_unit, alignment: 'right' }, { text: S.col_amount, alignment: 'right' }]
      .map(h => (typeof h === 'string' ? { text: h, bold: true, fillColor: '#eeeeee' } : { ...h, bold: true, fillColor: '#eeeeee' })),
    ...lines.map((l, i) => [
      { text: String(i + 1), alignment: 'right' },
      lineDescription(l, S),
      { text: `${l.qty} ${l.kind === 'base' ? S.unit_month : S.unit_pcs}`, alignment: 'right' },
      { text: formatMoney(l.unit_price, currency, lang), alignment: 'right' },
      { text: formatMoney(l.amount, currency, lang), alignment: 'right' },
    ]),
    [{ text: S.total, colSpan: 4, alignment: 'right', bold: true }, {}, {}, {}, { text: formatMoney(invoice.amount, currency, lang), alignment: 'right', bold: true }],
  ];

  const stamp = invoice.status === 'paid' ? S.status_paid : invoice.status === 'void' ? S.status_void : null;

  return {
    info: { title: `${S.title} ${number}`, author: seller.seller_name || 'ModESP Cloud', creator: 'ModESP Cloud' },
    defaultStyle: { font: 'Roboto', fontSize: 9 },
    pageSize: 'A4', pageMargins: [40, 46, 40, 56],
    footer: (currentPage, pageCount) => ({
      columns: [
        { text: `${S.footer} · ${number}`, fontSize: 7, color: '#777777' },
        { text: `${S.page} ${currentPage} ${S.of} ${pageCount}`, alignment: 'right', fontSize: 7, color: '#777777' },
      ],
      margin: [40, 18, 40, 0],
    }),
    content: [
      {
        columns: [
          { text: `${S.title} ${number}`, fontSize: 16, bold: true },
          stamp ? { text: stamp, alignment: 'right', fontSize: 14, bold: true, color: invoice.status === 'paid' ? '#2e7d32' : '#b71c1c' } : { text: '' },
        ],
        margin: [0, 0, 0, 10],
      },
      {
        columns: [
          block('', [[S.issued, formatDate(invoice.issued_at, lang)], [S.due, formatDate(invoice.due_at, lang)],
                     [S.period, `${formatDate(invoice.period_start, lang)} – ${formatDate(addDays(invoice.period_end, -1), lang)}`]]),
        ],
        margin: [0, 0, 0, 12],
      },
      {
        columns: [
          block(S.seller, [['', seller.seller_name], [S.tax_id, seller.seller_tax_id], [S.iban, seller.seller_iban], [S.bank, seller.seller_bank],
                           [S.address, seller.seller_address], [S.email, seller.seller_email]]),
          block(S.buyer, [['', buyer.legal_name], [S.tax_id, buyer.tax_id], [S.email, buyer.email]]),
        ],
        columnGap: 20,
        margin: [0, 0, 0, 14],
      },
      {
        table: { headerRows: 1, widths: [22, '*', 50, 70, 80], body: tableBody },
        layout: { hLineColor: () => '#cccccc', vLineColor: () => '#cccccc' },
        margin: [0, 0, 0, 12],
      },
      { text: [{ text: `${S.purpose}: `, bold: true }, S.purpose_text(number)], margin: [0, 0, 0, 6] },
      seller.invoice_note ? { text: seller.invoice_note, color: '#555555', fontSize: 8 } : { text: '' },
    ],
  };
}

function addDays(dateLike, n) {
  const d = new Date(dateLike);
  d.setUTCDate(d.getUTCDate() + n);
  return d;
}

async function render({ invoice, seller, lang }) {
  const doc = buildDocument({ invoice, seller, lang });
  const pdf = pdfmake.createPdf(doc);
  const buffer = await pdf.getBuffer();
  return Buffer.from(buffer);
}

module.exports = { render, buildDocument, formatMoney, formatDate, lineDescription, strings, STRINGS };
